alert("Welcome To JavaScript!");
var myname = prompt("what is your name?");
alert("Hello " + myname)
var firstname = prompt("enter your first name ");
var lastname = prompt(" enter your last name");
var fullname = firstname + lastname;
alert(fullname);
var favouritehobby = prompt("what is your favourite hobby?");
alert("my favourite hobby is " + favouritehobby);
var yearofbirth = prompt("current year?");
var age = prompt("what is your year of birth?");
var result = age - yearofbirth;
alert(result);
var length = prompt("enter the length of rectangle!");
var width = prompt("also enter the width of rectangle!");
var calculate = length * width;
alert(calculate);
alert("legal variables are the dollar sign underscore and starting with a letter");
alert("illegal variables are ending with underscore starting with digit and containing characters such as +");
alert("my age is 18");
alert("my friend's age is also 18");
var first = prompt("enter first number.");
var second = prompt("enter second number.");
var sum = first + second;
alert("the sum of 7 and 9 is " + sum);
alert("the result of 6 multiplied by 8 is:48");
alert("the remainder when 17 is divided by 5 is:2");
var one = prompt("enter the first number.");
var two =prompt("enter the second number.");
alert("sum:9 difference:-1 product:20 quotent:0.8 remainder:4");